[project]
name = "vivi-core"
version = "0.0.1"
description = "Vivi kernel and plugin API"
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"
