services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports: ["8787:8787"]
  ui:
    build:
      context: ./admin
      dockerfile: Dockerfile.ui
    environment:
      - API_BASE=http://localhost:8787
    ports: ["5173:80"]

