FROM python:3.12-slim
WORKDIR /app
COPY vivified_core/ vivified_core/
COPY vivified_api/ vivified_api/
COPY plugins/hello_py/ plugins/hello_py/
RUN pip install -U pip && pip install -e vivified_core -e vivified_api -e plugins/hello_py
ENV VIVI_TRAITS=demo
EXPOSE 8787
CMD ["vivified-api"]

