"""Add configuration tables

Revision ID: d3cb81c2e1de
Revises: ad39de79e841
Create Date: 2025-09-27 19:50:29.514513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3cb81c2e1de"
down_revision: Union[str, None] = "ad39de79e841"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'configurations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('value', sa.JSON(), nullable=False),
        sa.Column('plugin_id', sa.String(length=255), nullable=True),
        sa.Column('environment', sa.String(length=50), nullable=False),
        sa.Column('is_encrypted', sa.Boolean(), nullable=False),
        sa.Column('is_sensitive', sa.Boolean(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key', 'plugin_id', 'environment', name='uq_config_key_plugin_env')
    )
    op.create_table(
        'config_history',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('config_id', sa.String(length=36), nullable=False),
        sa.Column('old_value', sa.JSON(), nullable=True),
        sa.Column('new_value', sa.JSON(), nullable=False),
        sa.Column('changed_by', sa.String(length=36), nullable=True),
        sa.Column('change_reason', sa.String(length=500), nullable=True),
        sa.Column('changed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['config_id'], ['configurations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_history')
    op.drop_table('configurations')
    # ### end Alembic commands ###
