name: Docs Check
on:
  pull_request:
    branches: ["development", "main", "claude-test", "mkdocs"]

jobs:
  mkdocs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Build MkDocs (non-strict)
        run: mkdocs build || true
