name: MkDocs Deploy (mike)

on:
  push:
    branches: ["mkdocs"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Build and deploy with mike
        run: |
          mike deploy --push --update-aliases dev latest
          mike set-default --push latest
